### ISSUE TITLE
iOS UI binding Update

### ISSUE THREAD

**Issue by ShawnPavel** [vakrilov/native-script-accelerometer#5] opened 2017-05-16 15:56 UTC
I'm attempting to use the nativescript-accelerometer plugin to do a simple level app demonstration in Nativescript Angular.

The issue I'm running into is that the UI binding doesn't seem to update on iOS (works great on Android). The values are coming in great from the plugin but the UI doesn't update when bound to a local variable that is set to the x, y, z values as they come in.

One (potentially) important thing I've noticed is that the values will update on iOS if the device rotation changes. But only once.

This is reproducible in the demo for the plugin.

**Comment by vakrilov** [comment] 2017-05-17 10:23
Can you verify that the callback is actually fired?
* If the callback is **not** fired -> the problem is probably in the plugin.
* If the callback is fired but the binding is not updated ->  the problem is probably in the tns-core-modules.

**Comment by ShawnPavel** [comment] 2017-05-17 10:34
The callback definitely gets fired. If you rotate the app the values update on the screen during the rotation animation, but not once the orientation is locked in again.

**Comment by ShawnPavel** [comment] 2017-05-17 15:43
@vakrilov Any ideas on a way to fix or workaround this?

**Comment by vakrilov** [comment] 2017-05-18 08:37
I'm currently not able to test it as I need a real IOS device to do that.
One thing you can try is to use the [`orientationChanged` event of the application.](http://docs.nativescript.org/api-reference/modules/_application_.html#on) and try to stop/start the accelerometerUpdates again.

**Comment by demetrio812** [comment] 2017-05-30 13:12
Hello guys, I've tested the plugin and it's working on iOS for me...

@ShawnPavel one thing you can test to make the updates working in the UI is to use the NgZone.

Inject this in the constructor: `private zone: NgZone` and then use it like this:

```
me.zone.run(() => {
       me.exchangeMessage = x;
});
```

Note that as I'm running it inside the callback I've declare the variable `me` outside the callback like this: `let me = this;`

Let me know

Dem

**Comment by ShawnPavel** [comment] 2017-05-30 14:04
Hey @demetrio812. I tried to make some changes based on your suggestions but still it doesn't update live.

Here's my test applicaiton: https://github.com/ShawnPavel/nativescript-accelerometer-test

**Comment by demetrio812** [comment] 2017-05-30 16:10
I'll ry to test it when I have a bit of time, I'm triggering the updates using RxJs BehaviourSubject, you can also test that, I'll try to help when I can...

**Comment by ShawnPavel** [comment] 2017-06-01 11:26
@demetrio812  Do you have a sample of code out there somewhere I could reference?

**Comment by vakrilov** [comment] 2017-06-01 14:23
Good news! 
Looks like that the update callback is called in another thread which means that it is not allowed to make UI updates form there.
This is fixed now (thanks to @PanayotCankov for figuring this out).

The fix is published in npm -> `v. 2.0.1`

**Closed as completed by vakrilov** 2017-06-01 14:23 UTC

**Comment by ShawnPavel** [comment] 2017-06-01 22:27
@vakrilov I can confirm the newest version is fixed. @PanayotCankov deserves a raise or at the very least a high-five!

**Comment by demetrio812** [comment] 2017-06-03 12:01
Cool! Thanks for the update!
